version: "3.8"
services:
  api-database:
    image: mongo:latest
    container_name: "api-database"
    ports:
      - 27017:27017
  api:
    image: springboot:1.0
    container_name: "springboot-mongodb"
    ports:
      - 8081:8080
    links:
      - api-database